# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # NuGet dependencies for .NET projects
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependencies"
      - "nuget"
    reviewers:
      - "sunnamed434"

  # Python dependencies for documentation
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
      - "documentation"
    reviewers:
      - "sunnamed434"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "sunnamed434"
