name: "🐛 Bug Report"
description: Create a new ticket for a bug.
body:
  - type: textarea
    id: BitMono Version
    attributes:
      label: "Description"
      description: Please enter the used version of BitMono with the bug
      placeholder: 0.6.0-alpha.15
    validations:
      required: true
  - type: textarea
    id: .NET Version
    attributes:
      label: "Description"
      description: Please enter the used .NET version of target/obfuscating file 
      placeholder: .NET Framework 472
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: "Reproduction URL"
      description: Please enter your URL to provide a reproduction of the issue
      placeholder: ex. https://github.com/USERNAME/REPO-NAME, https://www.youtube.com/.. or some cloud service (eg, Google Drive)
    validations:
      required: false
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: applications
    attributes:
      label: "Applications"
      description: What type of BitMono application you've used ?
      multiple: true
      options:
        - CLI
        - GUI
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false