name: Artifacts for the BitMono CLI .NET (Core) 6.0

on:
  create:
    tags:
      - "*"

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x

      - name: Build
        run: dotnet build ./src/BitMono.CLI/BitMono.CLI.csproj /p:TargetFramework=net6.0 /p:BitMonoVersion=${{ github.ref_name }} /p:CreateBitMonoArtifacts=true --configuration Release

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: "./src/BitMono.CLI/BitMono-v${{ github.ref_name }}-CLI-net6.0.zip"
          if-no-files-found: error

  Release:
    needs: [Build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build/

      - name: Create Release & Upload Assets
        uses: ncipollo/release-action@v1
        with:
          name: v${{ github.ref_name }}
          tag: v${{ github.ref_name }}
          artifacts: "./build/BitMono-v${{ github.ref_name }}-CLI-net6.0.zip"
          token: ${{secrets.PAT}}
          prerelease: true
          allowUpdates: true