name: .NET Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: restore dotnet of BitMono.Host project
        run: dotnet restore src\BitMono.Host\BitMono.Host.csproj
        
      - name: build the BitMono.Host project
        run: msbuild src\BitMono.Host\BitMono.Host.csproj /p:Configuration=Release
        
      - name: restore dotnet of BitMono.Runtime project
        run: dotnet restore src\BitMono.Runtime\BitMono.Runtime.csproj
        
      - name: build the BitMono.Runtime project
        run: msbuild src\BitMono.Runtime\BitMono.Runtime.csproj /p:Configuration=Release
        
      - name: restore dotnet of BitMono.Shared project
        run: dotnet restore src\BitMono.Shared\BitMono.Shared.csproj
        
      - name: build the BitMono.Shared project
        run: msbuild src\BitMono.Shared\BitMono.Shared.csproj /p:Configuration=Release
        
      - name: restore dotnet of BitMono.CLI project
        run: dotnet restore src\BitMono.CLI\BitMono.CLI.csproj
        
      - name: build the BitMono.CLI project
        run: msbuild src\BitMono.CLI\BitMono.CLI.csproj /p:Configuration=Release
      
      - name: restore dotnet of BitMono.API project
        run: dotnet restore src\BitMono.API\BitMono.API.csproj
        
      - name: build the BitMono.API project
        run: msbuild src\BitMono.API\BitMono.API.csproj /p:Configuration=Release
        
      - name: restore dotnet of BitMono.Core project
        run: dotnet restore src\BitMono.Core\BitMono.Core.csproj
        
      - name: build the BitMono.Core project
        run: msbuild src\BitMono.Core\BitMono.Core.csproj /p:Configuration=Release
        
      - name: restore dotnet of BitMono.Protections project
        run: dotnet restore src\BitMono.Protections\BitMono.Protections.csproj
        
      - name: build the BitMono.Protections project
        run: msbuild src\BitMono.Protections\BitMono.Protections.csproj /p:Configuration=Release
        
      - name: restore dotnet of BitMono.Utilities project
        run: dotnet restore src\BitMono.Utilities\BitMono.Utilities.csproj
        
      - name: build the BitMono.Utilities project
        run: msbuild src\BitMono.Utilities\BitMono.Utilities.csproj /p:Configuration=Release
